### ISSUE TITLE
Can not spy Windows App SDK on UWP

### ISSUE THREAD

**Issue by wherewhere** [m417z/UWPSpy#1]
Select Target Framework as WinUI 3 it will crash, and select as UWP it said Failed to start spying...
![image](https://github.com/m417z/UWPSpy/assets/27689196/ac439dd2-0177-41f3-ad8a-dd651f86fdc8)

**Comment by m417z** [comment]
Can you post the app so that I could reproduce it?

**Comment by m417z** [comment]
> Select Target Framework as WinUI 3 it will crash

Can you capture a crash dump? You should be able to get it with the following steps:
* Open regedit
* Go to: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting`
* Create a key named `LocalDumps`
* Create a DWORD value named `DumpType` with value `2`
* Trigger the crash
* Go to the `%LocalAppData%\CrashDumps` folder, you should see a dump file in there

**Comment by wherewhere** [comment]
https://github.com/wherewhere/CoreAppUWP

**Comment by m417z** [comment]
I cloned and compiled the project but I'm not able to run it. What are the steps to get it to run?

**Comment by wherewhere** [comment]
It maybe you are not installed Windows App SDK or I don't know what...

**Comment by m417z** [comment]
I was able to run the project and UWPSpy works for me:

![image](https://github.com/m417z/UWPSpy/assets/4129781/01ec4add-4f8e-4a0a-bf29-fcc9e6153046)

Can you capture a crash dump? You should be able to get it with the following steps:
* Open regedit
* Go to: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting`
* Create a key named `LocalDumps`
* Create a DWORD value named `DumpType` with value `2`
* Trigger the crash
* Go to the `%LocalAppData%\CrashDumps` folder, you should see a dump file in there

**Comment by wherewhere** [comment]
[UWPSpy.exe.15172.7z](https://github.com/m417z/UWPSpy/files/13324960/UWPSpy.exe.15172.zip)
(It's a 7zip file)

**Comment by m417z** [comment]
I think this might fix it, can you give it a try?

[UWPSpy_fix_test.zip](https://github.com/m417z/UWPSpy/files/13325018/UWPSpy_fix_test.zip)

**Comment by wherewhere** [comment]
OK, It works.
![image](https://github.com/m417z/UWPSpy/assets/27689196/fe7ce535-0b88-4dc5-ba9a-a4e4dbbbcef8)

**Comment by m417z** [comment]
Thanks for confirming, I've released version 1.1.3 which contains the fix.
