### ISSUE TITLE
Unable to spy on start menu windows search

### ISSUE THREAD

**Issue by korolek13** [m417z/UWPSpy#3]
Can't find related process or it just don't work. I've tried spying on StartMenuExperienceHost.exe, but when I start searching something, UWPSpy hides itself. I've also tried spying on SearchHost.exe and SearchIndexer.exe, but to no avail. Is it expected behaviour?

**Comment by m417z** [comment]
Targeting SearchHost.exe works. Note that most of it is actually a web view control, so customizing the content will require a different approach.

https://github.com/m417z/UWPSpy/assets/4129781/28a6a740-478b-4a36-be95-ca95134bdaaf

**Comment by korolek13** [comment]
The issue is solved, I needed to target SearchHost one time and after an error refresh the process list and try again. Thank you

**Comment by m417z** [comment]
As far as I remember, there's an error until you search something at least once, probably because the UI isn't yes initialized.

**Comment by BirukTes** [comment]
Keeps disappearing on my system... using ExplorerPatcher - Win 10 taskbar and Win 11 menu... cannot inspect `SearchHost` and `StartMenuExperienceHost` process. Works when inspecting other windows such as Explorer.exe.
