### ISSUE TITLE
Please update avilable binary on Windows11

### ISSUE THREAD

**Issue by Sheephuman** [m417z/UWPSpy#7]
This is UWPSpy built in my environment
[avilable binary for Windows11](https://drive.google.com/file/d/1NZfbhiUnlOuU-BI8XT74a-xsZf5Z9jOd/view)

**Comment by m417z** [comment]
Binaries can be downloaded here:
https://ramensoftware.com/uwpspy

**Comment by Sheephuman** [comment]
not Work in Windows 11 23H2 22631.4112
